//hola frijoles
package formularios;
//</editor-fold>
import java.sql.*;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
/**
 *
 * @author GRAFITOS_VACIO
 */
public final class Alumno extends javax.swing.JFrame {

    /**
     * Creates new form Alumno
     */
    public Alumno() {
        initComponents();
        limpiar();
        bloquear();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("REGISTRO DE ALUMNO");
    }
    void limpiar(){
        Id.setText("");
        Nombre.setText("");
                                Apellido_P.setText("");
        Apellido_M.setText("");
        F_Nacimiento.setText("");
        CURP.setText("");
        RFC.setText("");
       }
     void bloquear(){
        Id.setEnabled(false);
        Nombre.setEnabled(false);
        Apellido_P.setEnabled(false);
        Apellido_M.setEnabled(false);
        F_Nacimiento.setEnabled(false);
        CURP.setEnabled(false);
        RFC.setEnabled(false);
        NUEVO.setEnabled(true);
        GUARDAR.setEnabled(false);
        CANCELAR.setEnabled(false);
     }
     void desbloquear(){
        Id.setEnabled(true);
        Nombre.setEnabled(true);
        Apellido_P.setEnabled(true);
        Apellido_M.setEnabled(true);
        F_Nacimiento.setEnabled(true);
        CURP.setEnabled(true);
        RFC.setEnabled(true);
        NUEVO.setEnabled(false);
        GUARDAR.setEnabled(true);
        CANCELAR.setEnabled(true);
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        DATOS_PERSONALES = new javax.swing.JDesktopPane();
        Id = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Apellido_M = new javax.swing.JTextField();
        RFC = new javax.swing.JTextField();
        F_Nacimiento = new javax.swing.JTextField();
        CURP = new javax.swing.JTextField();
        label16 = new java.awt.Label();
        Sexo = new java.awt.Choice();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        label22 = new java.awt.Label();
        label23 = new java.awt.Label();
        Apellido_P = new javax.swing.JTextField();
        CARDEX = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        DATOS_FAMILIARES = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        NUEVO = new javax.swing.JMenuItem();
        GUARDAR = new javax.swing.JMenuItem();
        CANCELAR = new javax.swing.JMenuItem();
        SALIR = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        DATOS_PERSONALES.setBackground(new java.awt.Color(0, 102, 102));

        Id.setText("jTextField3");
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        Id.setBounds(20, 20, 80, 30);
        DATOS_PERSONALES.add(Id, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Nombre.setText("jTextField3");
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        Nombre.setBounds(110, 20, 232, 30);
        DATOS_PERSONALES.add(Nombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Apellido_M.setText("jTextField3");
        Apellido_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        Apellido_M.setBounds(570, 20, 190, 30);
        DATOS_PERSONALES.add(Apellido_M, javax.swing.JLayeredPane.DEFAULT_LAYER);

        RFC.setText("jTextField3");
        RFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        RFC.setBounds(310, 80, 170, 30);
        DATOS_PERSONALES.add(RFC, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F_Nacimiento.setText("jTextField3");
        F_Nacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        F_Nacimiento.setBounds(20, 80, 90, 30);
        DATOS_PERSONALES.add(F_Nacimiento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CURP.setText("jTextField3");
        CURP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        CURP.setBounds(120, 80, 170, 30);
        DATOS_PERSONALES.add(CURP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label16.setText("SEXO");
        label16.setBounds(500, 80, 38, 20);
        DATOS_PERSONALES.add(label16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Sexo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Sexo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Sexo.setName(""); // NOI18N
        Sexo.setBounds(540, 80, 60, 30);
        DATOS_PERSONALES.add(Sexo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label17.setText("APELLIDO PATERNO");
        label17.setBounds(390, 50, 122, 20);
        DATOS_PERSONALES.add(label17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label18.setText("APELLIDO MATERNO");
        label18.setBounds(600, 50, 122, 20);
        DATOS_PERSONALES.add(label18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label19.setText("NOMBRE (S)");
        label19.setBounds(190, 50, 80, 20);
        DATOS_PERSONALES.add(label19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label20.setText("CONTROL");
        label20.setBounds(30, 50, 60, 20);
        DATOS_PERSONALES.add(label20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label21.setText("F. NACIMIENTO");
        label21.setBounds(20, 110, 90, 20);
        DATOS_PERSONALES.add(label21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label22.setText("CURP");
        label22.setBounds(180, 110, 40, 20);
        DATOS_PERSONALES.add(label22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label23.setText("RFC");
        label23.setBounds(380, 110, 30, 20);
        DATOS_PERSONALES.add(label23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Apellido_P.setText("jTextField3");
        Apellido_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        Apellido_P.setBounds(360, 20, 190, 30);
        DATOS_PERSONALES.add(Apellido_P, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CARDEX.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CARDEX.setText("CARDEX");
        CARDEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARDEXActionPerformed(evt);
            }
        });
        CARDEX.setBounds(440, 140, 160, 23);
        DATOS_PERSONALES.add(CARDEX, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setText("DATOS PERSONALES");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(20, 140, 160, 23);
        DATOS_PERSONALES.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        DATOS_FAMILIARES.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DATOS_FAMILIARES.setText("DATOS FAMILIARES");
        DATOS_FAMILIARES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATOS_FAMILIARESActionPerformed(evt);
            }
        });
        DATOS_FAMILIARES.setBounds(240, 140, 160, 23);
        DATOS_PERSONALES.add(DATOS_FAMILIARES, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setBounds(630, 70, 160, 100);
        DATOS_PERSONALES.add(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("MENU");

        NUEVO.setText("NUEVO");
        NUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOActionPerformed(evt);
            }
        });
        jMenu1.add(NUEVO);

        GUARDAR.setText("GUARDAR");
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });
        jMenu1.add(GUARDAR);

        CANCELAR.setText("CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });
        jMenu1.add(CANCELAR);

        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        jMenu1.add(SALIR);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DATOS_PERSONALES, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(DATOS_PERSONALES, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
Apellido_P.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
CURP.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
F_Nacimiento.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
Sexo.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
Apellido_M.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
Nombre.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       DATOS_PERSONALES obj=new DATOS_PERSONALES();
      obj.setVisible(true);
      dispose();
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void DATOS_FAMILIARESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATOS_FAMILIARESActionPerformed
         DATOS_FAMILIARES obj=new DATOS_FAMILIARES();
      obj.setVisible(true);
      dispose();
      // TODO add your handling code here:
    }//GEN-LAST:event_DATOS_FAMILIARESActionPerformed

    private void CARDEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARDEXActionPerformed
        CARDES obj=new CARDES();
      obj.setVisible(true);
      dispose(); 
      // TODO add your handling code here:
    }//GEN-LAST:event_CARDEXActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
bloquear();        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELARActionPerformed

    private void NUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOActionPerformed
desbloquear();
Nombre.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_NUEVOActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
conectar cc = new conectar();
connection cn=(connection) cc.conexion();
String  Nom = null,Ape_P,Ape_M,F_Nac,Curp,Rfs;
String sql= "";
Nom = Nombre.getText();
Ape_P = Apellido_P.getText();
Ape_M = Apellido_M.getText();
F_Nac = F_Nacimiento.getText();
Curp = CURP.getText();
Rfs = RFC.getText();
sql ="INSERT INTO Alumnos (Nombre,Apellido_P,Apellido_M,F_Nacimiento,CURP,RFC,Sexo)VALUES (?,?,?,?,?,?,?)";
try{
PreparedStatement pst=cn.PreparedStatement(sql);
pst.setString(1, Nom);
pst.setString(2, Ape_P);
pst.setString(3, Ape_M);
pst.setString(4, F_Nac);
pst.setString(5, Curp);
pst.setString(6, Rfs);

int n= pst.executeUpdate();
if (n>0){
    JOptionPane.showMessageDialog(null,"REGISTRO GUARDADO CON EXITO");
    bloquear();
}

}catch (SQLException ex){
    Logger.getLogger(Alumno.class.getName()).log(Level.SEVERE, null, ex);
    
}
    }//GEN-LAST:event_GUARDARActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_SALIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Alumno().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido_M;
    private javax.swing.JTextField Apellido_P;
    private javax.swing.JMenuItem CANCELAR;
    private javax.swing.JButton CARDEX;
    private javax.swing.JTextField CURP;
    private javax.swing.JButton DATOS_FAMILIARES;
    private javax.swing.JDesktopPane DATOS_PERSONALES;
    private javax.swing.JTextField F_Nacimiento;
    private javax.swing.JMenuItem GUARDAR;
    private javax.swing.JTextField Id;
    private javax.swing.JMenuItem NUEVO;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField RFC;
    private javax.swing.JMenuItem SALIR;
    private java.awt.Choice Sexo;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    // End of variables declaration//GEN-END:variables

    private static class connection {

        public connection() {
        }

        private PreparedStatement PreparedStatement(String sql) {
            throw new UnsupportedOperationException("Not yet implemented");
        }
    }
}
