
package formularios;

/**
 *
 * @author GRAFITOS_VACIO
 */
public class DATOS_PERSONALES extends javax.swing.JFrame {

    /**
     * Creates new form DATOS_PERSONALES
     */
    public DATOS_PERSONALES() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("DATOS PERSONALES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jScrollBar1 = new javax.swing.JScrollBar();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        javax.swing.JDesktopPane jDesktopPane2 = new javax.swing.JDesktopPane();
        Año_Engreso = new javax.swing.JTextField();
        Escuela_Bachillerato = new javax.swing.JTextField();
        Area_Engreso = new javax.swing.JTextField();
        label8 = new java.awt.Label();
        label11 = new java.awt.Label();
        Ciudad = new javax.swing.JTextField();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label19 = new java.awt.Label();
        Municipio_Nacimiento = new javax.swing.JTextField();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jTextField4 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        label23 = new java.awt.Label();
        label24 = new java.awt.Label();
        jTextField32 = new javax.swing.JTextField();
        label25 = new java.awt.Label();
        label26 = new java.awt.Label();
        label27 = new java.awt.Label();
        label28 = new java.awt.Label();
        jTextField21 = new javax.swing.JTextField();
        label33 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        Calle = new javax.swing.JTextField();
        label20 = new java.awt.Label();
        Numero = new javax.swing.JTextField();
        label21 = new java.awt.Label();
        label22 = new java.awt.Label();
        Colonia = new javax.swing.JTextField();
        C_Postal = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        Tipo_Preferente = new java.awt.Choice();
        Afilacion_Seguro = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        label29 = new java.awt.Label();
        label30 = new java.awt.Label();
        Afilacion = new javax.swing.JTextField();
        T_Sangre = new javax.swing.JTextField();
        label32 = new java.awt.Label();
        label34 = new java.awt.Label();
        Institucion = new javax.swing.JTextField();
        label18 = new java.awt.Label();
        label31 = new java.awt.Label();
        label35 = new java.awt.Label();
        label36 = new java.awt.Label();
        label37 = new java.awt.Label();
        Experiencia_Laboral = new javax.swing.JTextField();
        Empleo_Actual = new javax.swing.JTextField();
        Desde = new javax.swing.JTextField();
        Hasta = new javax.swing.JTextField();
        label38 = new java.awt.Label();
        Grupo_Indijena = new javax.swing.JTextField();
        Lengua_Indijena = new javax.swing.JTextField();
        label39 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        Municipio = new javax.swing.JTextField();
        label40 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jDesktopPane2.setBackground(new java.awt.Color(0, 102, 102));
        jDesktopPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Año_Engreso.setText("jTextField3");
        Año_Engreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Año_EngresoActionPerformed(evt);
            }
        });
        Año_Engreso.setBounds(430, 130, 80, 30);
        jDesktopPane2.add(Año_Engreso, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Escuela_Bachillerato.setText("jTextField3");
        Escuela_Bachillerato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Escuela_BachilleratoActionPerformed(evt);
            }
        });
        Escuela_Bachillerato.setBounds(30, 130, 180, 30);
        jDesktopPane2.add(Escuela_Bachillerato, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Area_Engreso.setText("jTextField3");
        Area_Engreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Area_EngresoActionPerformed(evt);
            }
        });
        Area_Engreso.setBounds(530, 130, 170, 30);
        jDesktopPane2.add(Area_Engreso, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label8.setText("AREA DE EGRESO");
        label8.setBounds(570, 160, 100, 30);
        jDesktopPane2.add(label8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label11.setText("CIUDAD ");
        label11.setBounds(280, 160, 50, 30);
        jDesktopPane2.add(label11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Ciudad.setText("jTextField3");
        Ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiudadActionPerformed(evt);
            }
        });
        Ciudad.setBounds(220, 130, 190, 30);
        jDesktopPane2.add(Ciudad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label16.setText("AÑO DE EGRESO");
        label16.setBounds(420, 160, 100, 30);
        jDesktopPane2.add(label16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label17.setText("ESCUELA DE BACHILLERATO");
        label17.setBounds(40, 160, 170, 30);
        jDesktopPane2.add(label17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label19.setText("MUNISIPIO DE NACIMIENTO");
        label19.setBounds(50, 90, 160, 20);
        jDesktopPane2.add(label19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Municipio_Nacimiento.setText("jTextField3");
        Municipio_Nacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Municipio_NacimientoActionPerformed(evt);
            }
        });
        Municipio_Nacimiento.setBounds(40, 60, 180, 30);
        jDesktopPane2.add(Municipio_Nacimiento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBackground(new java.awt.Color(0, 102, 102));

        jTextField4.setText("jTextField3");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.setBounds(430, 130, 80, 30);
        jDesktopPane3.add(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField10.setText("jTextField3");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.setBounds(30, 130, 180, 30);
        jDesktopPane3.add(jTextField10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField20.setText("jTextField3");
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jTextField20.setBounds(530, 130, 170, 30);
        jDesktopPane3.add(jTextField20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label23.setText("AREA DE EGRESO");
        label23.setBounds(570, 170, 100, 30);
        jDesktopPane3.add(label23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label24.setText("CIUDAD ");
        label24.setBounds(280, 160, 50, 30);
        jDesktopPane3.add(label24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField32.setText("jTextField3");
        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });
        jTextField32.setBounds(220, 130, 190, 30);
        jDesktopPane3.add(jTextField32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label25.setText("AÑO DE EGRESO");
        label25.setBounds(420, 160, 100, 30);
        jDesktopPane3.add(label25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label26.setText("ESCUELA DE BACHILLERATO");
        label26.setBounds(40, 160, 170, 30);
        jDesktopPane3.add(label26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label27.setText("PROCEDENCIA");
        label27.setBounds(50, 10, 150, 40);
        jDesktopPane3.add(label27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label28.setText("MUNISIPIO DE NACIMIENTO");
        label28.setBounds(50, 90, 160, 20);
        jDesktopPane3.add(label28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField21.setText("jTextField3");
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        jTextField21.setBounds(40, 60, 180, 30);
        jDesktopPane3.add(jTextField21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBounds(0, 0, 0, 0);
        jDesktopPane2.add(jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label33.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label33.setText("PROCEDENCIA");
        label33.setBounds(40, 10, 150, 40);
        jDesktopPane2.add(label33, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label12.setText("DOMICILIO");

        label13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label13.setText("CALLE");

        Calle.setText("jTextField3");
        Calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalleActionPerformed(evt);
            }
        });

        label20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label20.setText("COLONIA");

        Numero.setText("jTextField3");
        Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroActionPerformed(evt);
            }
        });

        label21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label21.setText("NUMERO");

        label22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label22.setText("C.POSTAL");

        Colonia.setText("jTextField3");
        Colonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColoniaActionPerformed(evt);
            }
        });

        C_Postal.setText("jTextField3");
        C_Postal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_PostalActionPerformed(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(0, 102, 102));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label14.setText("SERVICIO MEDICO");
        label14.setBounds(20, 10, 180, 30);
        jDesktopPane1.add(label14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label15.setText("AFILACION");
        label15.setBounds(580, 80, 70, 30);
        jDesktopPane1.add(label15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Tipo_Preferente.setBounds(20, 50, 90, 30);
        jDesktopPane1.add(Tipo_Preferente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Afilacion_Seguro.setText("jTextField3");
        Afilacion_Seguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Afilacion_SeguroActionPerformed(evt);
            }
        });
        Afilacion_Seguro.setBounds(380, 120, 110, 28);
        jDesktopPane1.add(Afilacion_Seguro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField24.setText("jTextField3");
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jTextField24.setBounds(120, 50, 180, 28);
        jDesktopPane1.add(jTextField24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label29.setText("AFILACION SEGURO SOCIAL");
        label29.setBounds(350, 150, 160, 30);
        jDesktopPane1.add(label29, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label30.setText("INSTITUCION");
        label30.setBounds(390, 80, 80, 30);
        jDesktopPane1.add(label30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Afilacion.setText("jTextField3");
        Afilacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfilacionActionPerformed(evt);
            }
        });
        Afilacion.setBounds(550, 50, 140, 28);
        jDesktopPane1.add(Afilacion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        T_Sangre.setText("jTextField3");
        T_Sangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_SangreActionPerformed(evt);
            }
        });
        T_Sangre.setBounds(170, 120, 110, 28);
        jDesktopPane1.add(T_Sangre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label32.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label32.setText("T. SANGRE");
        label32.setBounds(180, 150, 70, 30);
        jDesktopPane1.add(label32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label34.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label34.setText("TIPO PREFERENTE O OTRO");
        label34.setBounds(60, 80, 160, 30);
        jDesktopPane1.add(label34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Institucion.setText("jTextField3");
        Institucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstitucionActionPerformed(evt);
            }
        });
        Institucion.setBounds(340, 50, 180, 28);
        jDesktopPane1.add(Institucion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label18.setText("EXPERIENCIA LABORAL");

        label31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label31.setText("EXPERIENCIA PREVIA");

        label35.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label35.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label35.setText("EMPLEO ACTUAL");

        label36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label36.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label36.setText("DESDE");

        label37.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label37.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label37.setText("HASTA");

        Experiencia_Laboral.setText("jTextField3");
        Experiencia_Laboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Experiencia_LaboralActionPerformed(evt);
            }
        });

        Empleo_Actual.setText("jTextField3");
        Empleo_Actual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Empleo_ActualActionPerformed(evt);
            }
        });

        Desde.setText("jTextField3");
        Desde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesdeActionPerformed(evt);
            }
        });

        Hasta.setText("jTextField3");
        Hasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HastaActionPerformed(evt);
            }
        });

        label38.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label38.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label38.setText("GRUPO INDIGENA");

        Grupo_Indijena.setText("jTextField3");
        Grupo_Indijena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grupo_IndijenaActionPerformed(evt);
            }
        });

        Lengua_Indijena.setText("jTextField3");
        Lengua_Indijena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lengua_IndijenaActionPerformed(evt);
            }
        });

        label39.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label39.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label39.setText("LENGUA INDIJENA");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Vista Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Municipio.setText("jTextField3");
        Municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MunicipioActionPerformed(evt);
            }
        });

        label40.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label40.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label40.setText("MUNICIPIO");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(Calle, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C_Postal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Municipio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(label35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(label36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(label37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(Grupo_Indijena, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(Lengua_Indijena, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(Experiencia_Laboral, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Empleo_Actual, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Desde, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(Hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(label38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(label39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(23, 23, 23))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_Postal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Municipio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Experiencia_Laboral, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Desde, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Empleo_Actual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(label35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Grupo_Indijena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lengua_Indijena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Año_EngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Año_EngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Año_EngresoActionPerformed

    private void Escuela_BachilleratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Escuela_BachilleratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Escuela_BachilleratoActionPerformed

    private void CalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalleActionPerformed

    private void Area_EngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Area_EngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Area_EngresoActionPerformed

    private void CiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CiudadActionPerformed

    private void Municipio_NacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Municipio_NacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Municipio_NacimientoActionPerformed

    private void NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroActionPerformed

    private void ColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColoniaActionPerformed

    private void C_PostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_PostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_PostalActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void Experiencia_LaboralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Experiencia_LaboralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Experiencia_LaboralActionPerformed

    private void Afilacion_SeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Afilacion_SeguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Afilacion_SeguroActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void AfilacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfilacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AfilacionActionPerformed

    private void T_SangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_SangreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_SangreActionPerformed

    private void Empleo_ActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Empleo_ActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Empleo_ActualActionPerformed

    private void DesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesdeActionPerformed

    private void HastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HastaActionPerformed

    private void Grupo_IndijenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grupo_IndijenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grupo_IndijenaActionPerformed

    private void Lengua_IndijenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lengua_IndijenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lengua_IndijenaActionPerformed

    private void InstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstitucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstitucionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Alumno obj=new Alumno();
       obj.setVisible(true);
       dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MunicipioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DATOS_PERSONALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DATOS_PERSONALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DATOS_PERSONALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DATOS_PERSONALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DATOS_PERSONALES().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Afilacion;
    private javax.swing.JTextField Afilacion_Seguro;
    private javax.swing.JTextField Area_Engreso;
    private javax.swing.JTextField Año_Engreso;
    private javax.swing.JTextField C_Postal;
    private javax.swing.JTextField Calle;
    private javax.swing.JTextField Ciudad;
    private javax.swing.JTextField Colonia;
    private javax.swing.JTextField Desde;
    private javax.swing.JTextField Empleo_Actual;
    private javax.swing.JTextField Escuela_Bachillerato;
    private javax.swing.JTextField Experiencia_Laboral;
    private javax.swing.JTextField Grupo_Indijena;
    private javax.swing.JTextField Hasta;
    private javax.swing.JTextField Institucion;
    private javax.swing.JTextField Lengua_Indijena;
    private javax.swing.JTextField Municipio;
    private javax.swing.JTextField Municipio_Nacimiento;
    private javax.swing.JTextField Numero;
    private javax.swing.JTextField T_Sangre;
    private java.awt.Choice Tipo_Preferente;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField4;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private java.awt.Label label29;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label34;
    private java.awt.Label label35;
    private java.awt.Label label36;
    private java.awt.Label label37;
    private java.awt.Label label38;
    private java.awt.Label label39;
    private java.awt.Label label40;
    private java.awt.Label label8;
    // End of variables declaration//GEN-END:variables
}
