
package formularios;

/**
 *
 * @author GRAFITOS_VACIO
 */
public class DATOS_FAMILIARES extends javax.swing.JFrame {

    /**
     * Creates new form DATOS_FAMILIARES
     */
    public DATOS_FAMILIARES() {
        initComponents();
         limpiar();
         bloquear();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("DATOS FAMILIARES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        javax.swing.JDesktopPane jDesktopPane2 = new javax.swing.JDesktopPane();
        N_Madre = new javax.swing.JTextField();
        Vive1 = new javax.swing.JTextField();
        label8 = new java.awt.Label();
        label16 = new java.awt.Label();
        label19 = new java.awt.Label();
        Estado_Civil = new javax.swing.JTextField();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jTextField4 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        label23 = new java.awt.Label();
        label24 = new java.awt.Label();
        jTextField32 = new javax.swing.JTextField();
        label25 = new java.awt.Label();
        label26 = new java.awt.Label();
        label27 = new java.awt.Label();
        label28 = new java.awt.Label();
        jTextField21 = new javax.swing.JTextField();
        Tel = new javax.swing.JTextField();
        label18 = new java.awt.Label();
        Vive = new javax.swing.JTextField();
        label9 = new java.awt.Label();
        Tel_cel1 = new javax.swing.JTextField();
        label10 = new java.awt.Label();
        Tel1 = new javax.swing.JTextField();
        label12 = new java.awt.Label();
        Tel_Cel = new javax.swing.JTextField();
        label13 = new java.awt.Label();
        N_Padre = new javax.swing.JTextField();
        label20 = new java.awt.Label();
        javax.swing.JDesktopPane jDesktopPane4 = new javax.swing.JDesktopPane();
        jTextField5 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        label31 = new java.awt.Label();
        label32 = new java.awt.Label();
        label34 = new java.awt.Label();
        jTextField31 = new javax.swing.JTextField();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jTextField6 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        label35 = new java.awt.Label();
        label36 = new java.awt.Label();
        jTextField34 = new javax.swing.JTextField();
        label37 = new java.awt.Label();
        label38 = new java.awt.Label();
        label39 = new java.awt.Label();
        label40 = new java.awt.Label();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        label41 = new java.awt.Label();
        jTextField37 = new javax.swing.JTextField();
        label42 = new java.awt.Label();
        jTextField38 = new javax.swing.JTextField();
        label43 = new java.awt.Label();
        jTextField39 = new javax.swing.JTextField();
        label44 = new java.awt.Label();
        jTextField40 = new javax.swing.JTextField();
        label45 = new java.awt.Label();
        jTextField12 = new javax.swing.JTextField();
        label46 = new java.awt.Label();
        label33 = new java.awt.Label();
        jTextField8 = new javax.swing.JTextField();
        label17 = new java.awt.Label();
        Calle = new javax.swing.JTextField();
        Numero = new javax.swing.JTextField();
        Colonia = new javax.swing.JTextField();
        C_Postal = new javax.swing.JTextField();
        label22 = new java.awt.Label();
        label21 = new java.awt.Label();
        label29 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        label30 = new java.awt.Label();
        jTextField29 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        label48 = new java.awt.Label();
        label47 = new java.awt.Label();
        Correo_Electronico = new javax.swing.JTextField();
        C_Trabajo = new javax.swing.JTextField();
        label49 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Alumno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jDesktopPane2.setBackground(new java.awt.Color(0, 102, 102));
        jDesktopPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        N_Madre.setText("jTextField3");
        N_Madre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_MadreActionPerformed(evt);
            }
        });
        N_Madre.setBounds(40, 140, 390, 30);
        jDesktopPane2.add(N_Madre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Vive1.setText("jTextField3");
        Vive1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vive1ActionPerformed(evt);
            }
        });
        Vive1.setBounds(450, 140, 80, 30);
        jDesktopPane2.add(Vive1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label8.setText("TELEFONO");
        label8.setBounds(570, 170, 70, 30);
        jDesktopPane2.add(label8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label16.setText("VIVE");
        label16.setBounds(470, 110, 30, 30);
        jDesktopPane2.add(label16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label19.setText("ESTADO CIVIL");
        label19.setBounds(70, 50, 90, 20);
        jDesktopPane2.add(label19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Estado_Civil.setText("jTextField3");
        Estado_Civil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estado_CivilActionPerformed(evt);
            }
        });
        Estado_Civil.setBounds(40, 20, 180, 30);
        jDesktopPane2.add(Estado_Civil, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBackground(new java.awt.Color(0, 102, 102));

        jTextField4.setText("jTextField3");
        jTextField4.setBounds(430, 130, 80, 30);
        jDesktopPane3.add(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField10.setText("jTextField3");
        jTextField10.setBounds(30, 130, 180, 30);
        jDesktopPane3.add(jTextField10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField20.setText("jTextField3");
        jTextField20.setBounds(530, 130, 170, 30);
        jDesktopPane3.add(jTextField20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label23.setText("AREA DE EGRESO");
        label23.setBounds(570, 170, 100, 30);
        jDesktopPane3.add(label23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label24.setText("CIUDAD ");
        label24.setBounds(280, 160, 50, 30);
        jDesktopPane3.add(label24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField32.setText("jTextField3");
        jTextField32.setBounds(220, 130, 190, 30);
        jDesktopPane3.add(jTextField32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label25.setText("AÑO DE EGRESO");
        label25.setBounds(420, 160, 100, 30);
        jDesktopPane3.add(label25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label26.setText("ESCUELA DE BACHILLERATO");
        label26.setBounds(40, 160, 170, 30);
        jDesktopPane3.add(label26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label27.setText("PROCEDENCIA");
        label27.setBounds(50, 10, 150, 40);
        jDesktopPane3.add(label27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label28.setText("MUNISIPIO DE NACIMIENTO");
        label28.setBounds(50, 90, 160, 20);
        jDesktopPane3.add(label28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField21.setText("jTextField3");
        jTextField21.setBounds(40, 60, 180, 30);
        jDesktopPane3.add(jTextField21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBounds(0, 0, 0, 0);
        jDesktopPane2.add(jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Tel.setText("jTextField3");
        Tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelActionPerformed(evt);
            }
        });
        Tel.setBounds(550, 140, 110, 30);
        jDesktopPane2.add(Tel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label18.setText("VIVE");
        label18.setBounds(470, 170, 30, 30);
        jDesktopPane2.add(label18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Vive.setText("jTextField3");
        Vive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViveActionPerformed(evt);
            }
        });
        Vive.setBounds(450, 80, 80, 30);
        jDesktopPane2.add(Vive, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label9.setText("TELEFONO CEL");
        label9.setBounds(680, 170, 90, 30);
        jDesktopPane2.add(label9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Tel_cel1.setText("jTextField3");
        Tel_cel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tel_cel1ActionPerformed(evt);
            }
        });
        Tel_cel1.setBounds(670, 140, 110, 30);
        jDesktopPane2.add(Tel_cel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label10.setText("TELEFONO");
        label10.setBounds(570, 110, 70, 30);
        jDesktopPane2.add(label10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Tel1.setText("jTextField3");
        Tel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tel1ActionPerformed(evt);
            }
        });
        Tel1.setBounds(550, 80, 110, 30);
        jDesktopPane2.add(Tel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label12.setText("TELEFONO CEL");
        label12.setBounds(680, 110, 90, 30);
        jDesktopPane2.add(label12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Tel_Cel.setText("jTextField3");
        Tel_Cel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tel_CelActionPerformed(evt);
            }
        });
        Tel_Cel.setBounds(670, 80, 110, 30);
        jDesktopPane2.add(Tel_Cel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label13.setText("NOMBRE DE LA MADRE");
        label13.setBounds(50, 170, 130, 30);
        jDesktopPane2.add(label13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        N_Padre.setText("jTextField3");
        N_Padre.setBounds(40, 80, 390, 30);
        jDesktopPane2.add(N_Padre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label20.setText("NOMBRE DEL PADRE");
        label20.setBounds(60, 110, 130, 30);
        jDesktopPane2.add(label20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane4.setBackground(new java.awt.Color(0, 102, 102));
        jDesktopPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField5.setText("jTextField3");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.setBounds(40, 140, 390, 30);
        jDesktopPane4.add(jTextField5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField30.setText("jTextField3");
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });
        jTextField30.setBounds(450, 140, 80, 30);
        jDesktopPane4.add(jTextField30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label31.setText("TELEFONO");
        label31.setBounds(570, 170, 70, 30);
        jDesktopPane4.add(label31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label32.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label32.setText("VIVE");
        label32.setBounds(470, 110, 30, 30);
        jDesktopPane4.add(label32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label34.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label34.setText("ESTADO CIVIL");
        label34.setBounds(70, 50, 90, 20);
        jDesktopPane4.add(label34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField31.setText("jTextField3");
        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        jTextField31.setBounds(40, 20, 180, 30);
        jDesktopPane4.add(jTextField31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane5.setBackground(new java.awt.Color(0, 102, 102));

        jTextField6.setText("jTextField3");
        jTextField6.setBounds(430, 130, 80, 30);
        jDesktopPane5.add(jTextField6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField11.setText("jTextField3");
        jTextField11.setBounds(30, 130, 180, 30);
        jDesktopPane5.add(jTextField11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField33.setText("jTextField3");
        jTextField33.setBounds(530, 130, 170, 30);
        jDesktopPane5.add(jTextField33, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label35.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label35.setText("AREA DE EGRESO");
        label35.setBounds(570, 170, 100, 30);
        jDesktopPane5.add(label35, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label36.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label36.setText("CIUDAD ");
        label36.setBounds(280, 160, 50, 30);
        jDesktopPane5.add(label36, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField34.setText("jTextField3");
        jTextField34.setBounds(220, 130, 190, 30);
        jDesktopPane5.add(jTextField34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label37.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label37.setText("AÑO DE EGRESO");
        label37.setBounds(420, 160, 100, 30);
        jDesktopPane5.add(label37, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label38.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label38.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label38.setText("ESCUELA DE BACHILLERATO");
        label38.setBounds(40, 160, 170, 30);
        jDesktopPane5.add(label38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label39.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label39.setText("PROCEDENCIA");
        label39.setBounds(50, 10, 150, 40);
        jDesktopPane5.add(label39, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label40.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label40.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label40.setText("MUNISIPIO DE NACIMIENTO");
        label40.setBounds(50, 90, 160, 20);
        jDesktopPane5.add(label40, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField35.setText("jTextField3");
        jTextField35.setBounds(40, 60, 180, 30);
        jDesktopPane5.add(jTextField35, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane5.setBounds(0, 0, 0, 0);
        jDesktopPane4.add(jDesktopPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField36.setText("jTextField3");
        jTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField36ActionPerformed(evt);
            }
        });
        jTextField36.setBounds(550, 140, 110, 30);
        jDesktopPane4.add(jTextField36, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label41.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label41.setText("VIVE");
        label41.setBounds(470, 170, 30, 30);
        jDesktopPane4.add(label41, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField37.setText("jTextField3");
        jTextField37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField37ActionPerformed(evt);
            }
        });
        jTextField37.setBounds(450, 80, 80, 30);
        jDesktopPane4.add(jTextField37, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label42.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label42.setText("TELEFONO CEL");
        label42.setBounds(680, 170, 90, 30);
        jDesktopPane4.add(label42, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField38.setText("jTextField3");
        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });
        jTextField38.setBounds(670, 140, 110, 30);
        jDesktopPane4.add(jTextField38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label43.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label43.setText("TELEFONO");
        label43.setBounds(570, 110, 70, 30);
        jDesktopPane4.add(label43, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField39.setText("jTextField3");
        jTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField39ActionPerformed(evt);
            }
        });
        jTextField39.setBounds(550, 80, 110, 30);
        jDesktopPane4.add(jTextField39, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label44.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label44.setText("TELEFONO CEL");
        label44.setBounds(680, 110, 90, 30);
        jDesktopPane4.add(label44, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField40.setText("jTextField3");
        jTextField40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField40ActionPerformed(evt);
            }
        });
        jTextField40.setBounds(670, 80, 110, 30);
        jDesktopPane4.add(jTextField40, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label45.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label45.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label45.setText("NOMBRE DE LA MADRE");
        label45.setBounds(50, 170, 130, 30);
        jDesktopPane4.add(label45, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField12.setText("jTextField3");
        jTextField12.setBounds(40, 80, 390, 30);
        jDesktopPane4.add(jTextField12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label46.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label46.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label46.setText("NOMBRE DEL PADRE");
        label46.setBounds(60, 110, 130, 30);
        jDesktopPane4.add(label46, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane4.setBounds(0, 0, 0, 0);
        jDesktopPane2.add(jDesktopPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label33.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label33.setText("TUTOR");

        jTextField8.setText("jTextField3");

        label17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label17.setText("NOMBRE DEL TUTOR");

        Calle.setText("jTextField3");
        Calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalleActionPerformed(evt);
            }
        });

        Numero.setText("jTextField3");
        Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroActionPerformed(evt);
            }
        });

        Colonia.setText("jTextField3");
        Colonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColoniaActionPerformed(evt);
            }
        });

        C_Postal.setText("jTextField3");
        C_Postal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_PostalActionPerformed(evt);
            }
        });

        label22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label22.setText("C.POSTAL");

        label21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label21.setText("COLONIA");

        label29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label29.setText("NUMERO");

        label14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label14.setText("CALLE");

        label15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label15.setText("ORIGUINARIO");

        jTextField27.setText("jTextField3");
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });

        jTextField28.setText("jTextField3");
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });

        label30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label30.setText("CORREO ELECTRONICO");

        jTextField29.setText("jTextField3");
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });

        jTextField41.setText("jTextField3");
        jTextField41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField41ActionPerformed(evt);
            }
        });

        jTextField42.setText("jTextField3");
        jTextField42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField42ActionPerformed(evt);
            }
        });

        label48.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label48.setText("TELEFONO CEL");

        label47.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label47.setText("TELEFONO");

        Correo_Electronico.setText("jTextField3");
        Correo_Electronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Correo_ElectronicoActionPerformed(evt);
            }
        });

        C_Trabajo.setText("jTextField3");
        C_Trabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_TrabajoActionPerformed(evt);
            }
        });

        label49.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label49.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label49.setText("CENTRO DE TRABAJO");

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Vista Principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane2)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(label47, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(label48, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)
                                    .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Calle, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(C_Trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Correo_Electronico, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(label49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                                    .addComponent(jButton2))))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(121, 121, 121)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(C_Postal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(134, 134, 134)
                                    .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Calle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(C_Postal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Correo_Electronico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_Trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label49, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Estado_CivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estado_CivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Estado_CivilActionPerformed

    private void N_MadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_MadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N_MadreActionPerformed

    private void Vive1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vive1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vive1ActionPerformed

    private void TelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelActionPerformed

    private void ViveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViveActionPerformed

    private void Tel_cel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tel_cel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tel_cel1ActionPerformed

    private void Tel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tel1ActionPerformed

    private void Tel_CelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tel_CelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tel_CelActionPerformed

    private void CalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalleActionPerformed

    private void NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroActionPerformed

    private void ColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColoniaActionPerformed

    private void C_PostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_PostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_PostalActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36ActionPerformed

    private void jTextField37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField37ActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed

    private void jTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39ActionPerformed

    private void jTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField40ActionPerformed

    private void jTextField41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField41ActionPerformed

    private void jTextField42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField42ActionPerformed

    private void Correo_ElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Correo_ElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Correo_ElectronicoActionPerformed

    private void C_TrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_TrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_TrabajoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Alumno obj=new Alumno();
        obj.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Alumno obj=new Alumno();
        obj.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DATOS_FAMILIARES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DATOS_FAMILIARES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DATOS_FAMILIARES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DATOS_FAMILIARES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DATOS_FAMILIARES().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C_Postal;
    private javax.swing.JTextField C_Trabajo;
    private javax.swing.JTextField Calle;
    private javax.swing.JTextField Colonia;
    private javax.swing.JTextField Correo_Electronico;
    private javax.swing.JTextField Estado_Civil;
    private javax.swing.JTextField N_Madre;
    private javax.swing.JTextField N_Padre;
    private javax.swing.JTextField Numero;
    private javax.swing.JTextField Tel;
    private javax.swing.JTextField Tel1;
    private javax.swing.JTextField Tel_Cel;
    private javax.swing.JTextField Tel_cel1;
    private javax.swing.JTextField Vive;
    private javax.swing.JTextField Vive1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private java.awt.Label label10;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private java.awt.Label label29;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label34;
    private java.awt.Label label35;
    private java.awt.Label label36;
    private java.awt.Label label37;
    private java.awt.Label label38;
    private java.awt.Label label39;
    private java.awt.Label label40;
    private java.awt.Label label41;
    private java.awt.Label label42;
    private java.awt.Label label43;
    private java.awt.Label label44;
    private java.awt.Label label45;
    private java.awt.Label label46;
    private java.awt.Label label47;
    private java.awt.Label label48;
    private java.awt.Label label49;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables

